### ISSUE TITLE
Error when using Windows Live ID or 2 factor authentication user

### ISSUE THREAD

**Issue by robinlior** [Inovativ/Feedback#11]
![image](https://cloud.githubusercontent.com/assets/20713109/24331736/225c27b2-1243-11e7-85f1-741350cde9e1.png)

I suggest to use the website login page and not implement the login ....

Also for 2 factor authentication:

![image](https://cloud.githubusercontent.com/assets/20713109/24331754/5b2c6764-1243-11e7-9a2d-5e849f1f51c9.png)

Regards,
Lior.

**Comment by katomel4** [comment]
as far as i know it works only on CSP subscriptions (not PAYG, EA etc)

**Comment by JanVanMeirvenne** [comment]
Thanks for your feedback.

We won't support live-id and MFA because of the following reasons:

- Live-ID: this is (as katomel4 mentioned) not always supported depending on Azure subscription type etc. Also, Microsoft is pushing the usage of AAD, while deprecating Live-Id usage. Because of this, the effort of adding and maintaining Live-ID support is too high in relations to the pay-off in the future.

- MFA: this is a mixed bag: for automated, unattended usage, it is a nogo as the login will be performed silently. We could add it in the GUI, but as the GUI uses the unattended powershell functions, a lot of code rewrite would be needed, which would only fix issues for a limited set of scenario's. Therefore it is recommended to either (temporarily) disable MFA for accounts that will use the solution. Another option (paid) is to use the privileged access feature in AAD premium and use MFA to request role elevation (to obtain admin rights) and then allow the post-activation operations to occur without MFA. More info: https://gotoguy.blog/2016/09/09/how-to-enable-azure-mfa-for-online-powershell-modules-that-dont-support-mfa/
